declare namespace Cloudflare {
  interface Env {
    DB: D1Database
    GHL_LOCATION_ID: string
    GHL_PIPELINE_ID: string
    GHL_PIPELINE_STAGE_ID: string
    GHL_PRIVATE_INTEGRATION_TOKEN: string
    SITE_URL?: string
    WEBSITE_CRM_DISPATCH_ENABLED?: string
    WEBSITE_EXTERNAL_TRACKING_ENABLED?: string
    WEBSITE_CRM_MODE?: string
    WEBSITE_CRM_TEST_EMAIL?: string
    WEBSITE_CRM_TEST_PHONE?: string
    WEBSITE_TEST_SUPPRESSION_APPROVED?: string
    WEBSITE_ACCEPTANCE_CONTACT_ID?: string
    WEBSITE_VERIFICATION_ENABLED?: string
    WEBSITE_ACCEPTANCE_WORKFLOWS_APPROVED?: string
    WEBSITE_RECOVERY_DISPATCH_ENABLED?: string
    WEBSITE_RETURNING_NURTURE_APPROVED?: string
    WEBSITE_RETURNING_NURTURE_STAGE_ID?: string
    STUDIO_BRIDGE_SECRET?: string
    STUDIO_BRIDGE_ORIGIN?: string
  }
}
